### ISSUE TITLE
Move window to space (on same display) not working

### ISSUE THREAD

**Issue by jessevdp** [mogenson/PaperWM.spoon#52]
Hey,

First off, I'm really enjoying PaperWM.spoon. It's really interesting to use something like this on MacOS. Kudos for that.

---

It seems like I can't move a window from one space to another on the same monitor.

A demo:

https://github.com/user-attachments/assets/1e2aa48c-8913-47a4-a37d-318a0398891b

Here you see me

1. Switch from space 4 to space 3
2. Switch back from space 3 to space 4
3. Attempt to move the window from space 4 to space 3
4. Notice that the window didn't move
5. Switch back to space 4 and see that its still there

It seems that the window is moved out of the tiling layer, but remains in the previous space.

I can move a window from a space on a separate screen to another screen. Curious.

Any clue what's happening?

Thanks! ✌️

**Comment by mogenson** [comment]
Hey, sorry for the delay. Could you check a few things:

1) Make sure you're using the latest version of Hammerspoon and have cloned the latest version of PaperWM.spoon

2) Use the `switch_space_l`, `switch_space_r`, `switch_space_1`, etc actions instead of the MacOS swipe left / right or `ctrl` + arrow key methods to switch space. This lets PaperWM try to keep sync between what space it thinks is focused and what space is actually visible on screen.

3) Make sure you've selected / deselected the required Mission Control options in https://github.com/mogenson/PaperWM.spoon?tab=readme-ov-file#installation step #2

4) Can you copy and paste the output from the Hammerspoon Console when invoking the `move_window_1`, etc action.

**Comment by mogenson** [comment]
I added a way to move a window from one space to another by automating the mouse cursor in Mission Control. Please see if #57 fixes this issue.

**Comment by mogenson** [comment]
Merged #57

**Comment by alper** [comment]
> The current work around is to [toggle the window as floating](https://github.com/mogenson/PaperWM.spoon/blob/6d1ec0a60f844499a09bf1b0b33b29255d3b5a16/README.md?plain=1#L75) and manually drag the window to the new space. Toggle the window back from floating and it will be tiled on the new space.

I've noticed that this works.

I've noticed the same that with trying to move windows from my laptop screen to my main monitor, it's very unreliable wether it'll actually move the window to the other window and tiling group.
