### ISSUE TITLE
Microsoft Office apps are left as floating windows

### ISSUE THREAD

**Issue by epstein6** [mogenson/PaperWM.spoon#55]
Hello,

I'm having a bit of trouble using PaperWM.spoon with Microsoft Office apps (Excel, Powerpoint).  They are just treated as regular floating windows instead of being managed.  Is there something I need to add to my configuration for these?  I'm mostly just using the default config from the README.

Thanks.

**Comment by mogenson** [comment]
There's a known issue with MS Office windows being detected as multiple tabs instead of one window.

Do you get this notification popup when you open a MS office window?
https://github.com/mogenson/PaperWM.spoon/blob/main/init.lua#L567-L571

I don't have Office installed to test, but try removing lines 567 to 571 locally and let me know the MS Office windows are tilled correctly. Note, this change will add a blank gap when opening a tab in a Finder window or a Terminal window, so you'll just have to avoid those actions.

**Comment by epstein6** [comment]
I don't think I've ever seen that popup, but removing the return there does fix the problem.  Is there some dependency I'm missing to get popups?  And is removing that a good solution at least for me, or is there anything better?

**Comment by mogenson** [comment]
You may need to allow notifications from Hammerspoon within MacOS settings.

Glad that change fixed things. We still need that check to avoid treating one Finder or Terminal window with multiple tabs as separate windows.

Are the MS Office windows tiles correctly or are there big, window sized, gaps between the MS Office window and the next left or right window?

**Comment by epstein6** [comment]
Thanks, that may be it.

Yeah, the Office windows are tiled fine, certainly not like the finder tabs.

**Comment by mogenson** [comment]
I installed MS Word. It looks like there a tab for each item in the ribbon menu up top. However these tabs do not show up as separate windows with unique window IDs like the Finder and Terminal tabs.

There's still no way to query which window a tab is part of so we need to know at window creation time whether to allow a tab for a MS Office window or reject a tab for a Finder window. Let's try doing this by application type. Instead of maintaining an allow-list of applications where tabs are not windows, let's start with a block-list of applications where tabs are windows. Right now, this is just the Apple applications.

See if PR #56 works for you.

**Comment by epstein6** [comment]
Thanks!  Yeah, looks like that PR works fine for me.
