### ISSUE TITLE
can't switch desktop on other display.

### ISSUE THREAD

**Issue by hansbogert** [mogenson/PaperWM.spoon#9]
when I press `switch_space_2` which is on my other display, mission control opens but doesn't actually give focus to the space. I can then only press escape, and focus returns to the previous space.

**Comment by mogenson** [comment]
Ok, I see this too. Switch-to-space or move-window-to-space will open that space in Mission Control but the mouse and active menubar remains on the previous display.

I'll have to look to see what APIs are available to focus on a visible space. Programmatically moving and clicking the mouse seems like a fragile and bad idea.

In the mean time, the window tiling is robust to you manually opening mission control to switch spaces and clicking to focus a new space with your mouse. You'll still need to use the move-window-to-space keyboard shortcut to tell the tiling to "let go" of the window.

**Comment by shmygol** [comment]
I have the same problem. Currently my screens have only one space and for me it works more reliably if I just comment out `gotoSpace` in `PaperWM:switchToSpace` function. Thus instead of using Mission Control to switch between spaces PaperWM focus a window on a different screen, which triggers switching. Unfortunately I don't know how would it work with mayn spaces on a single screen.

**Comment by mogenson** [comment]
I added a focusSpace() method. This attempts to focus and keep focus on a newly selected space by either focusing a window that is on that space or by clicking the menubar of that space. This is about as much as I can do to keep MacOS from switching focus back to a space with another window of the same application.
